### ISSUE TITLE
Delete line and undo dont work as expected on Ubuntu

### ISSUE THREAD

**Issue by TiagoDillenburg** [yatli/fvim#121] opened 2020-02-24 01:54 UTC
![Peek_23-02-2020_22-05](https://user-images.githubusercontent.com/13285472/75124578-eecd5400-568e-11ea-81a0-59a62a568553.gif)

After the first dd (delete line) command, the next undo and dd require a movement key to finish executing, except if the command deletes up to an empty line (2dd or 3dd to empty line). I ran fvim without init.vim (fvim -u NONE) to prevent conflicts.

LANG=pt_BR.UTF-8
Ubuntu 19.10
Nvim 0.4.3

**Comment by yatli** [comment] 2020-02-24 04:12
Thanks for reporting.
Can repro on WSL.
Not only `dd`, I also see the problem with `x`

**Comment by yatli** [comment] 2020-02-24 04:17
Looks like a regression by upgrading dependencies.

**Comment by yatli** [comment] 2020-02-24 04:54
Again this: `InvalidateVisuals()` doesn't trigger `Render`

**Comment by TiagoDillenburg** [comment] 2020-02-24 13:29
Version v0.2-132-ge81f09a is working. And Nvim welcome screen is also showing on this version.

**Comment by yatli** [comment] 2020-02-25 07:40
Working with upstream devs on this.

**Comment by yatli** [comment] 2020-03-21 19:06
Should be fixed with https://github.com/yatli/fvim/pull/129
There was a workaround against the upstream `InvalidateVisuals()` bug but it failed because of updated layout. This is now fixed.

**Comment by yatli** [comment] 2020-03-21 19:06
@TiagoDillenburg could you give it a go?

**Comment by TiagoDillenburg** [comment] 2020-03-31 02:35
I'm sorry. My linux setup is broken now and I'm afraid I wont be able to tested any time soon.

**Comment by yatli** [comment] 2020-03-31 03:24
No worry, I've got a fresh Linux installation recently :)

**Closed** 2020-03-31 04:08 UTC
Labels: bug, plat-linux
